version: '{build}-{branch}'

os: Visual Studio 2019

build: off

install:
    - wsl sudo sed --in-place 's/Prompt=lts/Prompt=normal/' /etc/update-manager/release-upgrades
    - wsl sudo do-release-upgrade

test_script:
 msbuild /t:Build /p:Configuration=Release "./test/test.sln" -maxcpucount
